# Generated by Django 3.1.8 on 2021-04-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_shell', '0003_auto_20210411_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionresult',
            name='error_json',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='executionresult',
            name='output_json',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
