# Generated by Django 3.1.8 on 2021-04-13 06:20

from django.db import migrations, models
import turtle_shell.utils


class Migration(migrations.Migration):

    dependencies = [
        ("turtle_shell", "0004_auto_20210411_1223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionresult",
            name="error_json",
            field=models.JSONField(
                decoder=turtle_shell.utils.EnumAwareDecoder,
                default=dict,
                encoder=turtle_shell.utils.EnumAwareEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="executionresult",
            name="input_json",
            field=models.JSONField(
                decoder=turtle_shell.utils.EnumAwareDecoder,
                encoder=turtle_shell.utils.EnumAwareEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="executionresult",
            name="output_json",
            field=models.JSONField(
                decoder=turtle_shell.utils.EnumAwareDecoder,
                default=dict,
                encoder=turtle_shell.utils.EnumAwareEncoder,
                null=True,
            ),
        ),
    ]
