# Generated by Django 3.1.8 on 2021-04-13 13:23

from django.db import migrations, models
import turtle_shell.utils


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_shell', '0005_auto_20210412_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionresult',
            name='traceback',
            field=models.JSONField(decoder=turtle_shell.utils.EnumAwareDecoder, default=dict, encoder=turtle_shell.utils.EnumAwareEncoder, null=True),
        ),
    ]
