# Generated by Django 3.1.8 on 2021-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turtle_shell", "0006_executionresult_traceback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionresult",
            name="traceback",
            field=models.TextField(default=""),
        ),
    ]
